import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/theme/app_theme.dart';

class ReportsNotebookView extends ConsumerWidget {
  const ReportsNotebookView({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // In a real implementation, this would consume a provider state with the report data
    // generated by the DataAnalystAgent.
    return Container(
      padding: const EdgeInsets.all(24),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Left Panel: Sources / Citations
          Expanded(
            flex: 1,
            child: Container(
              decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.05),
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.white10),
              ),
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text("Sources", style: TextStyle(color: Colors.white70, fontWeight: FontWeight.bold, fontSize: 16)),
                  const SizedBox(height: 16),
                  _buildSourceItem("BigQuery: Monthly Performance", Icons.storage),
                  _buildSourceItem("Drive: Q1 Strategy Doc", Icons.description),
                  _buildSourceItem("Gmail: Client Feedback", Icons.email),
                ],
              ),
            ),
          ),
          const SizedBox(width: 24),
          // Right Panel: Main Content (Notebook LM style)
          Expanded(
            flex: 3,
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                   const Text("Monthly Campaign Analysis", style: TextStyle(color: Colors.white, fontSize: 28, fontWeight: FontWeight.bold)),
                   const SizedBox(height: 24),
                   
                   _buildSectionTitle("Executive Summary"),
                   _buildSectionBody("The campaign has shown a strong upward trend in engagement, driven primarily by the new creative assets deployed on social channels. ROI has increased by 15% compared to last month."),
                   
                   _buildSectionTitle("Performance Metrics"),
                   _buildSectionBody("Key metrics indicate a healthy funnel:"),
                   _buildMetricRow("Impressions", "1.2M", "+12%"),
                   _buildMetricRow("CTR", "2.4%", "+0.3%"),
                   _buildMetricRow("Conversions", "850", "+5%"),
                   
                   _buildSectionTitle("Strategic Recommendations"),
                   _buildSectionBody("Based on the data, we recommend doubling down on the video content format and exploring a new audience segment in the 25-34 demographic."),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSourceItem(String title, IconData icon) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        children: [
          Icon(icon, color: AppTheme.primary, size: 18),
          const SizedBox(width: 8),
          Expanded(child: Text(title, style: const TextStyle(color: Colors.white70, fontSize: 13))),
        ],
      ),
    );
  }
  
  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(top: 24, bottom: 8),
      child: Text(title, style: const TextStyle(color: AppTheme.primary, fontSize: 18, fontWeight: FontWeight.bold)),
    );
  }
  
  Widget _buildSectionBody(String text) {
    return Text(text, style: const TextStyle(color: Colors.white, fontSize: 15, height: 1.6));
  }
  
  Widget _buildMetricRow(String label, String value, String change) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        children: [
          SizedBox(width: 120, child: Text("- $label:", style: const TextStyle(color: Colors.white70))),
          Text(value, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
          const SizedBox(width: 12),
          Container(
             padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
             decoration: BoxDecoration(color: Colors.green.withOpacity(0.2), borderRadius: BorderRadius.circular(4)),
             child: Text(change, style: const TextStyle(color: Colors.green, fontSize: 12)),
          )
        ],
      ),
    );
  }
}
