// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'Android options are not configured. Run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows options are not configured. Run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux options are not configured. Run `flutterfire configure` to generate options.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMuHqc2OlaQdgVXUvQSsbpU9_DDwb3nNA',
    appId: '1:1096509611056:web:bf9733b80ef18d8a4de1f5',
    messagingSenderId: '1096509611056',
    projectId: 'inhausbrain',
    authDomain: 'inhausbrain.firebaseapp.com',
    storageBucket: 'inhausbrain.firebasestorage.app',
    measurementId: 'G-05VDXB7D8N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7OFEeMqbEHA_t5L12-uKbmVke_sbzQOU',
    appId: '1:1096509611056:ios:8aa015397b2fe6054de1f5',
    messagingSenderId: '1096509611056',
    projectId: 'inhausbrain',
    storageBucket: 'inhausbrain.firebasestorage.app',
    iosBundleId: 'com.inhausbrain.inhausBrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7OFEeMqbEHA_t5L12-uKbmVke_sbzQOU',
    appId: '1:1096509611056:ios:8aa015397b2fe6054de1f5',
    messagingSenderId: '1096509611056',
    projectId: 'inhausbrain',
    storageBucket: 'inhausbrain.firebasestorage.app',
    iosBundleId: 'com.inhausbrain.inhausBrain',
  );
}
