import 'package:uuid/uuid.dart';

enum TransactionType {
  income,
  expense,
  tax_payment,
  internal_transfer
}

enum ExpenseCategory {
  ad_spend,
  software_subscription,
  payroll,
  rent,
  utilities,
  office_supplies,
  travel,
  taxes_sri, // Specialized for Ecuador
  other
}

enum ReportType {
  pl_statement, // Profit & Loss
  tax_projection_sri, // SRI Tax Projection
  burn_rate_analysis,
  ad_spend_breakdown
}

class FinanceTransaction {
  final String id;
  final String title;
  final double amount;
  final TransactionType type;
  final ExpenseCategory? category;
  final DateTime date;
  final String? clientId; // For Ad Spend tracking per client
  final String? receiptUrl; // URL to PDF/Image of invoice
  final Map<String, dynamic> metadata;

  FinanceTransaction({
    required this.id,
    required this.title,
    required this.amount,
    required this.type,
    this.category,
    required this.date,
    this.clientId,
    this.receiptUrl,
    this.metadata = const {},
  });

  factory FinanceTransaction.create({
    required String title,
    required double amount,
    required TransactionType type,
    ExpenseCategory? category,
    String? clientId,
    DateTime? date,
  }) {
    return FinanceTransaction(
      id: const Uuid().v4(),
      title: title,
      amount: amount,
      type: type,
      category: category,
      date: date ?? DateTime.now(),
      clientId: clientId,
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'title': title,
    'amount': amount,
    'type': type.index,
    'category': category?.index,
    'date': date.toIso8601String(),
    'clientId': clientId,
    'receiptUrl': receiptUrl,
    'metadata': metadata,
  };

  factory FinanceTransaction.fromJson(Map<String, dynamic> json) {
    return FinanceTransaction(
      id: json['id'],
      title: json['title'],
      amount: json['amount'].toDouble(),
      type: TransactionType.values[json['type'] ?? 0],
      category: json['category'] != null ? ExpenseCategory.values[json['category']] : null,
      date: DateTime.parse(json['date']),
      clientId: json['clientId'],
      receiptUrl: json['receiptUrl'],
      metadata: json['metadata'] ?? {},
    );
  }
}

class FinanceReport {
  final String id;
  final String title;
  final ReportType type;
  final String contentMarkdown; // Generated by AI
  final DateTime generatedAt;
  final Map<String, double>? keyMetrics; // e.g., {"Total Revenue": 10000, "Net Profit": 2000}

  FinanceReport({
    required this.id,
    required this.title,
    required this.type,
    required this.contentMarkdown,
    required this.generatedAt,
    this.keyMetrics,
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'title': title,
    'type': type.index,
    'contentMarkdown': contentMarkdown,
    'generatedAt': generatedAt.toIso8601String(),
    'keyMetrics': keyMetrics,
  };

  factory FinanceReport.fromJson(Map<String, dynamic> json) {
    return FinanceReport(
      id: json['id'],
      title: json['title'],
      type: ReportType.values[json['type'] ?? 0],
      contentMarkdown: json['contentMarkdown'],
      generatedAt: DateTime.parse(json['generatedAt']),
      keyMetrics: (json['keyMetrics'] as Map<String, dynamic>?)?.map(
        (k, v) => MapEntry(k, v.toDouble()),
      ),
    );
  }
}

class FinanceSnapshot {
  final double totalRevenue;
  final double totalExpenses;
  final double netProfit;
  final double currentBurnRate;
  final double estimatedTaxLiability;

  FinanceSnapshot({
    required this.totalRevenue,
    required this.totalExpenses,
    required this.netProfit,
    required this.currentBurnRate,
    required this.estimatedTaxLiability,
  });
}
